kind: pipeline
name: build
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: build-test
    image: golang:1.15
    commands:
      - apt-get update && apt-get install -y libjpeg-dev libwebp-dev -q
      - go mod download
      - make build
      - ls ./
      - rm -rf ./app.tar
      - tar -cvf ./app.tar -C ./bin vault
      - tar -rvf ./app.tar -C ./docker/vault wait-for-it.sh
      - tar -rvf ./app.tar -C ./ ./templates
      - ls ./
    when:
      branch: never
  - name: compress
    image: golang:1.15
    commands:
      - rm -rf ./app.tar
      - tar -cvf ./app.tar -C ./ .
  - name: rsync
    image: drillster/drone-rsync
    environment:
      RSYNC_KEY:
        from_secret: rsync_key
      RSYNC_USER:
        from_secret: rsync_user
      PLUGIN_ARGS: -zz -O --no-perms
      SOME_VAR: asdasd
    settings:
      port: 22522
      hosts:
        - vault48.org
      source: ./
      user: ${rsync_user}
      key: ${rsync_key}
      target: /opt/deploys/drone/vault/staging/backend
      include:
        - "app.tar"
      exclude:
        - "*"
      script:
        - cd /opt/deploys/drone/vault/staging/backend
        - tar -xf ./app.tar -C ./
        - docker-compose up -d



