kind: pipeline
name: build
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: compress
    image: golang:1.15
    commands:
      - rm -rf ./app.tar
      - tar -cvf ./app.tar -C ./ .
  - name: upload
    image: drillster/drone-rsync
    when:
      branch: never
    environment:
      RSYNC_KEY:
        from_secret: rsync_key
      RSYNC_USER:
        from_secret: rsync_user
      PLUGIN_ARGS: -zz -O --no-perms
    settings:
      port: 22522
      hosts:
        - vault48.org
      source: ./
      user: ${rsync_user}
      key: ${rsync_key}
      target: /opt/deploys/drone/vault/staging/backend
      include:
        - "app.tar"
      exclude:
        - "*"
      script:
        - cd /opt/deploys/drone/vault/staging/backend
        - tar -xf ./app.tar -C ./
        - docker-compose build
        - docker-compose up -d
  - name: build
    image: appleboy/drone-ssh
    settings:
      host: vault48.org
      username: derek
      key:
        from_secret: rsync_key
      envs:
        - rsync_user
      port: 22522
      script:
        - mkdir /tmp/drone
        - export RSYNC_USER=$rsync_user
        - echo $RSYNC_USER > /tmp/drone/1.log
        - echo $RSYNC_USER



