kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: build-test
    image: golang:1.15
    commands:
      - apt-get update && apt-get install -y libjpeg-dev libwebp-dev -q
      - go mod download
      - make build
  - name: deploy-dev
    image: golang:1.15
    when:
      branch: develop
      event:
        - push
    environment:
      env_location:
        from_secret: VAULT_STAGING_BACKEND_ENV
    commands:
      - echo "HI"
      - echo $env_location
      - ls ./
