kind: pipeline
name: build
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: compress
    image: golang:1.15
    commands:
      - rm -rf ./app.tar
      - tar -cvf ./app.tar -C ./ .
  - name: upload-develop
    image: drillster/drone-rsync
    when:
      branch: develop
    environment:
      RSYNC_KEY:
        from_secret: rsync_key
      RSYNC_USER:
        from_secret: rsync_user
      RSYNC_PATH:
        from_secret: rsync_path_develop
      PLUGIN_ARGS: -zz -O --no-perms
    settings:
      port: 22522
      hosts:
        - vault48.org
      source: ./
      user: ${rsync_user}
      key: ${rsync_key}
      target: /tmp/vault-golang-${DRONE_BRANCH}
      include:
        - "app.tar"
      exclude:
        - "*"
  - name: build
    image: appleboy/drone-ssh
    environment:
      RSYNC_PATH:
        from_secret: rsync_path_develop
    settings:
      host: vault48.org
      username: derek
      key:
        from_secret: rsync_key
      envs: [rsync_path]
      port: 22522
      script:
        - mkdir -p $${RSYNC_PATH}/${DRONE_BRANCH}
        - tar -xf /tmp/vault-golang-${DRONE_BRANCH} -C $${RSYNC_PATH}/${DRONE_BRANCH}
#        - echo ${DRONE_BRANCH}
#        - echo $${RSYNC_PATH} > /tmp/drone/7.log
#        - tar -xf /tmp/vault-staging-backend/app.tar -C $${RSYNC_PATH}
#        - cd $${RSYNC_PATH}
#        - ls ./
#        - docker-compose build
#        - docker-compose up -d
