Port: 7777
Host: localhost
DB: 
  URI: login:password@tcp(db)/database?parseTime=true
  Debug: true
Vk:
  ClientId: 123456
  ClientSecret: SECRET_API_KEY_FROM_VK
  CallbackUrl: http://localhost:7777/oauth/vkontakte/process/
API:
  Debug: false
  TlsFiles: []
  Host: 
Smtp:
  Host: postfix # docker setup
  Port: 25
  User: # empty for docker
  Password: # empty for docker
  From: Robot Mailer <robot@vault48.org>
Frontend:
  ResetUrl: /restore/
  PublicHost: localhost
Uploads:
  Path: /tmp/uploads/here
  MaxSizeMb: 200
Google:
  ApiKey: YouTubeApiKeyHere
  ClientId: 123456123123-someScrambledC0deHere.apps.googleusercontent.com
  ClientSecret: sEcr-ETAPIkeYFROMGoogle
  CallbackUrl: http://localhost:7777/oauth/google/process
JWT:
  Secret: CHANGE_ME!!!
Debug: false