Port: 7777
DB:
  URI: login:password@tcp(db)/database?parseTime=true
  Debug: true # debug queries
Vk:
  ClientId: 123456
  ClientSecret: SECRET_API_KEY_FROM_VK
  CallbackUrl: http://localhost:7777/oauth/vkontakte/process/
API:
  Debug: false # debug api calls
  TlsFiles: []
Smtp:
  Host: postfix # docker setup
  Port: 25
  User: # empty for docker
  Password: # empty for docker
  From: Robot Mailer <robot@vault48.org>
Frontend:
  ResetUrl: /restore/
  PublicHost: localhost
Uploads:
  Path: /tmp/uploads/here
  MaxSizeMb: 200
Google:
  ApiKey: YouTubeApiKeyHere
  ClientId: 123456123123-someScrambledC0deHere.apps.googleusercontent.com
  ClientSecret: sEcr-ETAPIkeYFROMGoogle
  CallbackUrl: http://localhost:7777/oauth/google/process
JWT:
  Secret: CHANGE_ME!!!
Debug: false # die on errors
Notifications:
  Vk:
    Enabled: true
    # User api key, should be fetched with appId, which is not of web type
    # https://oauth.vk.com/authorize?client_id=appId&display=page&redirect_uri=https://oauth.vk.com/blank.html&scope=offline,photos,wall,groups&response_type=token&v=5.65
    ApiKey: e048e83950d5e8ef1067d3cce40c87931f930eea6273213622b97f490ff6d64cfa4d67205525c3adabf05
    Group: 46909317
    CooldownMins: 30 # How minutes to wait before publishing
    PurgeAfterDays: 7 # Days, after unsent notification will be purged
    UrlPrefix: https://staging.vault48.org
