Port: 7777
Host: localhost
DB: 
  URI: login:password@tcp(127.0.0.1)/database?parseTime=true
  Debug: true
Vk:
  ClientId: 123456
  ClientSecret: SECRET_API_KEY_FROM_VK
API:
  Debug: false
  TlsFiles: []
  Host: 
