version: '3'
services:
  db:
    restart: always
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: 'user'
      MYSQL_PASS: 'pass'
      MYSQL_DATABASE: 'vault'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
  app:
    restart: always
    build:
      context: .
      dockerfile: docker/vault/Dockerfile
    ports:
      - ${EXPOSE}:${EXPOSE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/go
      - /var/bbs/:/var/bbs/
    environment:
      EXPOSE: ${EXPOSE}
    entrypoint: ./wait-for-it.sh -t 90 db:3306 -- ./vault serve
    depends_on:
      - db
  mail:
    restart: always
      build:
        context: .
        dockerfile: docker/postfix/Dockerfile
      ports:
        - 25:25
      volumes:
        - /etc/localtime:/etc/localtime:ro
volumes:
  node_modules:
